name: Generate snake
on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Generate snake
      uses: Platane/snk@v3
      with:
        github_user_name: junaidify
        output: github-contribution-grid-snake.svg
